name: Test WebGrab Plus

on:
  workflow_dispatch:

jobs:
  test-webgrab:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Install .NET 9 runtime
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '9.0.x'

      - name: Download WebGrab+Plus
        run: |
          wget -O webgrab.tar.gz "http://webgrabplus.com/sites/default/files/download/SW/V5.3.0/WebGrabPlus_V5.3_install.tar.gz"

      - name: Extract WebGrab+Plus
        run: |
          mkdir webgrab
          tar -xzf webgrab.tar.gz -C webgrab

      - name: Show files
        run: |
          find webgrab

      - name: Install WebGrab+Plus
        run: |
          cd webgrab
          chmod +x install.sh
          ./install.sh

      - name: Run WebGrab+Plus
        run: |
          ~/.wg++/run.net.sh
